### ISSUE TITLE
Chrome downloader blocks

### ISSUE THREAD

**Issue by Teremok** [jingweno/hacker-menu#19] opened 2015-09-17 23:48 UTC
Chrome downloader blocks ZIP file with binary after downloads from https://hackermenu.io/ page. The reasons are listed here https://support.google.com/chrome/answer/6261569?p=ib_download_blocked&hl=en&rd=1

**Comment by jingweno** [comment] 2015-09-18 03:54
@Teremok I assume you were downloading it from Windows since I wasn't able to reproduce it on Mac:

![screen shot 2015-09-17 at 8 51 18 pm](https://cloud.githubusercontent.com/assets/169064/9951646/e8c1359a-5d7d-11e5-80b7-28c510e3c48f.png)

Actually we only have Mac builds now so even if Chrome didn't warn you you won't be able to run it. And for Windows, we will make sure it can be downloaded okay without such warning.

Please follow https://github.com/jingweno/hacker-menu/issues/18 for Windows builds.

**Comment by Teremok** [comment] 2015-09-18 04:00
@jingweno unfortunately I have downloaded it from mac. And looks exactly the same:
https://www.evernote.com/shard/s12/sh/c7660dd6-6064-4a40-b358-a983ce13e718/1752c54191d32fe7

**Comment by jingweno** [comment] 2015-09-18 04:32
@Teremok Hmm...you're right. I just reproduced on OSX. Is this Chrome feature something new? I'm sure I was able to download it without problem a few days ago...

**Comment by jingweno** [comment] 2015-09-18 04:33
We could use dmg instead of zip if that will mute Chrome's warning

**Comment by jingweno** [comment] 2015-09-18 04:44
Ah, okay, I think it's in general a GitHub Releases issue. Any download from GitHub Releases are having this issue, for example, I tried to download the atom mac build from https://github.com/atom/atom/releases/download/v1.0.13/atom-mac.zip:

<img width="170" alt="screen shot 2015-09-17 at 9 42 06 pm" src="https://cloud.githubusercontent.com/assets/169064/9952080/3d351892-5d85-11e5-827b-7d8a8e616325.png">

**Comment by Teremok** [comment] 2015-09-18 04:53
@jingweno confirmed! Seems that this is an updated Chrome policy, or some troubles with Github SSL certificate. \

**Comment by lokywin** [comment] 2015-09-18 05:08
This seems like a new issue. I was able to download previously just fine. But I now do get the warning too.
![screen shot 2015-09-17 at 10 05 52 pm](https://cloud.githubusercontent.com/assets/545713/9952270/90cda2be-5d88-11e5-8058-e5f6694f54cf.png)

**Comment by technoweenie** [comment] 2015-09-18 21:43
Hey all, I just pushed out a fix for this. Let me know if you still have problems.

**Comment by jingweno** [comment] 2015-09-18 22:05
@technoweenie:

> Hey all, I just pushed out a fix for this. Let me know if you still have problems.

Nice! I verified the problem is gone. Thanks for looking into this! :cake:

**Closed by jingweno** 2015-09-18 22:05 UTC
